- name: Set up apt-key for controlplane repo
  ansible.builtin.apt_key:
    url: https://europe-north1-apt.pkg.dev/doc/repo-signing-key.gpg
    state: present

- name: Set up controlplane repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://europe-north1-apt.pkg.dev/projects/naisdevice controlplane main"
    state: present
