#!/usr/bin/env bash
# vim:ft=bash
#MISE description="Package msi"
#MISE depends=["build:windows"]

set -o errexit
set -o pipefail
set -o nounset

# Windows MSI requires X.X.X.X version format
version="${VERSION}.0"
outfile=$OUTFILE

cert_file=$(mktemp --suffix .crt)
key_file=$(mktemp --suffix .key)
trap 'echo "Removing temporary files" && rm -f "$key_file" "$cert_file"' EXIT

echo "$MSI_SIGN_CERT" >"$cert_file"
echo "$MSI_SIGN_KEY" >"$key_file"

for bin in bin/windows-client/*; do
	if [[ "$bin" != *.exe ]]; then
		echo "Skipping non-exe file $bin"
		continue
	fi
	mise run package:windows:sign-exe "$bin" "$cert_file" "$key_file"
done

sign_opts="-Dcert_file=$cert_file -Dkey_file=$key_file"
makensis -NOCD "-DOUTFILE=$outfile" "-DVERSION=$version" "$sign_opts" mise/tasks/package/windows/naisdevice.nsi
