#!/usr/bin/env bash
# vim:ft=bash
#MISE description="Package msi"
#MISE depends=["build:windows","icon:windows"]

set -o errexit
set -o pipefail

if [ -z "$MSI_SIGN_CERT" ]; then
	echo "MSI_SIGN_CERT not set."
	exit 1
fi

if [ -z "$MSI_SIGN_KEY" ]; then
	echo "MSI_SIGN_KEY not set."
	exit 1
fi

cert_file=$(mktemp --suffix .crt)
key_file=$(mktemp --suffix .key)
trap 'rm -f "$key_file" "$cert_file"' INT TERM EXIT

echo "$MSI_SIGN_CERT" >"$cert_file"
echo "$MSI_SIGN_KEY" >"$key_file"

for bin in bin/windows-client/*; do
	if [[ "$bin" != *.exe ]]; then
		echo "Skipping non-exe file $bin"
		continue
	fi
	mise run package:windows:sign-exe "$bin" "$cert_file" "$key_file"
done

sign_opts="-Dcert_file=$cert_file -Dkey_file=$key_file"
makensis "-DVERSION=$VERSION" "$sign_opts" mise/tasks/package/windows/naisdevice.nsi
