inpackage: true
dir: "{{ .InterfaceDir }}"
filename: "mock_{{ .InterfaceName | snakecase }}.go"
template-data:
  unroll-variadic: true
packages:
  github.com/nais/device/internal/apiserver/auth:
    interfaces:
      SessionStore:
  github.com/nais/device/internal/apiserver/bucket:
    interfaces:
      Client:
      Object:
  github.com/nais/device/internal/apiserver/database:
    interfaces:
      Database:
  github.com/nais/device/pkg/pb:
    interfaces:
      APIServerClient:
      APIServer_GetGatewayConfigurationClient:
      APIServer_GetDeviceConfigurationClient:
      DeviceHelperClient:
  github.com/nais/device/internal/wireguard:
    interfaces:
      NetworkConfigurer:
  github.com/nais/device/internal/notify:
    interfaces:
      Notifier:
  github.com/nais/device/internal/device-agent/runtimeconfig:
    interfaces:
      RuntimeConfig:
  github.com/nais/device/internal/helper:
    interfaces:
      OSConfigurator:
