with-expecter: true
disable-version-string: true
inpackage: true
dir: "{{.InterfaceDir}}"
filename: "mock_{{.InterfaceNameSnake}}.go"
packages:
  github.com/nais/device/pkg/apiserver/auth:
    interfaces:
      SessionStore:
  github.com/nais/device/pkg/apiserver/bucket:
    interfaces:
      Client:
      Object:
  github.com/nais/device/pkg/apiserver/database:
    interfaces:
      APIServer:
  github.com/nais/device/pkg/pb:
    interfaces:
      APIServerClient:
      APIServer_GetGatewayConfigurationClient:
  github.com/nais/device/pkg/wireguard:
    interfaces:
      NetworkConfigurer:
  github.com/nais/device/pkg/notify:
    interfaces:
      Notifier:
  github.com/nais/device/pkg/device-agent/runtimeconfig:
    interfaces:
      RuntimeConfig:
  github.com/nais/device/pkg/helper:
    interfaces:
      OSConfigurator:
