@startuml

hide empty description
top to bottom direction

state enabled <<choice>>
state bootstrapped <<choice>>
state authenticated <<choice>>

[*] --> Running

Running --> enabled
enabled --> bootstrapped : user wants to be connected
enabled --> Disconnecting : user wants to disconnect

bootstrapped -> Bootstrapping : needs bootstrap
bootstrapped --> authenticated : already bootstrapped

Bootstrapping: obtain oauth2 token for bootstrap API from Azure
Bootstrapping: obtain device IP and API server connection info
Bootstrapping: write bootstrap configuration file
Bootstrapping: write tunnel configuration file
Bootstrapping --> authenticated

authenticated -> Authenticating : needs auth
authenticated --> SyncConfig : already authed
Authenticating: only run if API server gateway health is OK
Authenticating: obtain oauth2 auth code from Azure
Authenticating: exchange auth code with session key from API server

Authenticating --> SyncConfig
SyncConfig: only run if API server gateway health is OK
SyncConfig: only run if interval X reached
SyncConfig: retrieve personalized list of gateways from API server
SyncConfig: write tunnel configuration file

SyncConfig --> HealthCheck
HealthCheck: only run if interval Y reached
HealthCheck: ping each gateway in turn
HealthCheck: set next health check interval based on API server availability

HealthCheck --> Running

Disconnecting --> Running
Disconnecting: delete tunnel configuration file

@enduml