version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - "./fixtures/schema.sql:/docker-entrypoint-initdb.d/0001-schema.sql:ro"
      - "./fixtures/data.sql:/docker-entrypoint-initdb.d/0002-data.sql:ro"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
