// Code generated by "stringer -type=GuiEvent ./internal/systray"; DO NOT EDIT.

package systray

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VersionClicked-0]
	_ = x[StateInfoClicked-1]
	_ = x[ConnectClicked-2]
	_ = x[QuitClicked-3]
	_ = x[DeviceLogClicked-4]
	_ = x[HelperLogClicked-5]
	_ = x[ZipLogsClicked-6]
	_ = x[LogClicked-7]
	_ = x[AutoConnectClicked-8]
	_ = x[BlackAndWhiteClicked-9]
	_ = x[AcceptableUseClicked-10]
}

const _GuiEvent_name = "VersionClickedStateInfoClickedConnectClickedQuitClickedDeviceLogClickedHelperLogClickedZipLogsClickedLogClickedAutoConnectClickedBlackAndWhiteClickedAcceptableUseClicked"

var _GuiEvent_index = [...]uint8{0, 14, 30, 44, 55, 71, 87, 101, 111, 129, 149, 169}

func (i GuiEvent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_GuiEvent_index)-1 {
		return "GuiEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GuiEvent_name[_GuiEvent_index[idx]:_GuiEvent_index[idx+1]]
}
