# This file was generated by nais/device. DO NOT EDIT.
cask "naisdevice-tenant" do
  version "$VERSION"
  version_scheme 1
  name "naisdeice-tenant"
  desc "naisdevice is a mechanism enabling developers to connect to internal resources in a secure and friendly manner."
  homepage "https://docs.nais.io/operate/naisdevice/how-to/install/"

  if Hardware::CPU.intel?
    url "$NAISDEVICE_TENANT_MACOS_AMD64_URL"
    sha256 "$NAISDEVICE_TENANT_MACOS_AMD64_HASH_BASE16"
    pkg "naisdevice-tenant_macos_amd64.pkg"
  end
  if Hardware::CPU.arm?
    url "$NAISDEVICE_TENANT_MACOS_ARM64_URL"
    sha256 "$NAISDEVICE_TENANT_MACOS_ARM64_HASH_BASE16"
    pkg "naisdevice-tenant_macos_arm64.pkg"
  end

  uninstall pkgutil: "io.nais.device"
end
