# This file was generated by $REPO$. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  system ? builtins.currentSystem,
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}: let
  name = "$NAME";
  version = "$VERSION";
  repo = "$REPO";

  shaMap = {
    x86_64-linux = "$SHA_LINUX_AMD64_BASE32";
    aarch64-linux = "$SHA_LINUX_ARM64_BASE32";
    x86_64-darwin = "$SHA_DARWIN_AMD64_BASE32";
    aarch64-darwin = "$SHA_DARWIN_ARM64_BASE32";
  };

  urlMap = {
    x86_64-linux = "https://github.com/${repo}/releases/download/${version}/${name}_linux_amd64_${version}.tar.gz";
    aarch64-linux = "https://github.com/${repo}/releases/download/${version}/${name}_linux_arm64_${version}.tar.gz";
    x86_64-darwin = "https://github.com/${repo}/releases/download/${version}/${name}_darwin_amd64_${version}.tar.gz";
    aarch64-darwin = "https://github.com/${repo}/releases/download/${version}/${name}_darwin_arm64_${version}.tar.gz";
  };
in
  stdenvNoCC.mkDerivation {
    pname = "${name}";
    version = "${version}";
    src = fetchurl {
      url = urlMap.${system};
      sha256 = shaMap.${system};
    };

    sourceRoot = ".";

    nativeBuildInputs = [installShellFiles];

    installPhase = ''
      mkdir -p $out/bin
      cp -vr ./nais $out/bin/nais
    '';
    postInstall = ''
      installShellCompletion ./completions/*
    '';

    system = system;

    meta = {
      sourceProvenance = [lib.sourceTypes.binaryNativeCode];

      platforms = [
        "aarch64-darwin"
        "aarch64-linux"
        "x86_64-darwin"
        "x86_64-linux"
      ];
    };
  }
