#!/usr/bin/env bash
# vim:ft=bash
#MISE description="Package deb"
#MISE depends=["build:linux"]

set -o errexit
set -o pipefail
set -o nounset

rm ./naisdevice*.deb

fpm \
	--verbose \
	--output-type deb \
	--input-type dir \
	--name "naisdevice${SUFFIX}" \
	--version "${1:-Unknown}" \
	--vendor "NAV / nais team" \
	--maintainer "NAV / nais team" \
	--description "naisdevice is a mechanism enabling NAVs developers to connect to internal resources in a secure and friendly manner" \
	--url https://doc.nais.io/operate/naisdevice/how-to/install \
	--depends jq \
	--depends sed \
	--depends wireguard \
	--depends libnss3-tools \
	--depends openssl \
	--after-remove assets/linux/postrm \
	--after-install assets/linux/postinstall \
	--after-upgrade assets/linux/postinstall \
	--deb-systemd assets/linux/naisdevice-helper.service \
	--deb-systemd-enable \
	--deb-systemd-auto-start \
	--deb-systemd-restart-after-upgrade \
	"bin/linux-client/naisdevice-helper=/usr/sbin/naisdevice-helper" \
	"bin/linux-client/naisdevice-agent=/usr/bin/naisdevice-agent" \
	"bin/linux-client/naisdevice-systray=/usr/bin/naisdevice-systray" \
	"assets/linux/naisdevice.desktop=/usr/share/applications/" \
	"assets/certs/=/usr/share/ca-certificates/nav/" \
	"assets/linux/icon/=/usr/share/icons/hicolor/" \
	"assets/linux/apparmor-local-wg=/etc/apparmor.d/local/wg"
