- name: Ensure packages is installed
  ansible.builtin.apt:
    name:
      - gnupg
      - prometheus-node-exporter
      - apt-transport-https
      - ca-certificates
      - curl
      - ca-certificates
      - cron
      - vim
      - unattended-upgrades
      - debconf # used by ansible to configure deb packages
      - debconf-utils # used by ansible to configure deb packages

- name: make sure unattented-upgrades is enabled
  ansible.builtin.debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: "true"
    vtype: select
