#!/bin/bash

set -o errexit
set -o pipefail

pushd "$(dirname "${0}")"

rm -f ./naisdevice*.exe

# Rewrite from versions like this 2022-09-23-090728 to 1.20220223.090728
# If version not in correct format, do not pass VERSION at all
VERSION=${1:-develop}
version_opt=""
if date -d"${VERSION%-*}" &> /dev/null ; then
  isodate=$(date -d"${VERSION%-*}" +%Y%m%d)
  isotime="${VERSION##*-}"
  version_opt="-DVERSION=1.${isodate}.${isotime}.0"
fi

sign_opts=""
if [[ -n "${MSI_SIGN_CERT}" && -n "${MSI_SIGN_KEY}" ]]; then
  sign_opts="-DCERT_FILE=${MSI_SIGN_CERT} -DKEY_FILE=${MSI_SIGN_KEY}"
fi

makensis ${version_opt} ${sign_opts} ./naisdevice.nsi

popd
