#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

rm -f ./gateway-agent*.deb

fpm \
	--verbose \
	--output-type deb \
	--input-type dir \
	--name gateway-agent \
	--version "${1:-Unknown}" \
	--vendor "NAV / nais team" \
	--maintainer "NAV / nais team" \
	--description "gateway-agent connects to a naisdevice-apiserver for WireGuard config and forwards traffic for devices based" \
	--url https://github.com/nais/device \
	--deb-systemd packaging/controlplane/gateway-agent/gateway-agent.service \
	--deb-systemd-enable \
	--deb-systemd-auto-start \
	--deb-systemd-restart-after-upgrade \
	--depends wireguard \
	packaging/controlplane/gateway-agent/gateway-agent=/etc/default/gateway-agent \
	bin/controlplane/gateway-agent=/usr/bin/gateway-agent
