// Code generated by mockery v2.10.0. DO NOT EDIT.

package auth

import mock "github.com/stretchr/testify/mock"

// MockUsernamePasswordAuthenticator is an autogenerated mock type for the UsernamePasswordAuthenticator type
type MockUsernamePasswordAuthenticator struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: username, password
func (_m *MockUsernamePasswordAuthenticator) Authenticate(username string, password string) error {
	ret := _m.Called(username, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
