// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddDevice(ctx context.Context, arg AddDeviceParams) error
	AddGateway(ctx context.Context, arg AddGatewayParams) error
	AddSession(ctx context.Context, arg AddSessionParams) error
	GetDeviceByID(ctx context.Context, id int32) (*Device, error)
	GetDeviceByPublicKey(ctx context.Context, publicKey string) (*Device, error)
	GetDeviceBySerialAndPlatform(ctx context.Context, arg GetDeviceBySerialAndPlatformParams) (*Device, error)
	GetDevices(ctx context.Context) ([]*Device, error)
	GetGatewayByName(ctx context.Context, name string) (*Gateway, error)
	GetGateways(ctx context.Context) ([]*Gateway, error)
	GetMostRecentDeviceSession(ctx context.Context, deviceID int32) (*GetMostRecentDeviceSessionRow, error)
	GetSessionByKey(ctx context.Context, key *string) (*GetSessionByKeyRow, error)
	GetSessions(ctx context.Context) ([]*GetSessionsRow, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error
	UpdateGateway(ctx context.Context, arg UpdateGatewayParams) error
	UpdateGatewayDynamicFields(ctx context.Context, arg UpdateGatewayDynamicFieldsParams) error
}

var _ Querier = (*Queries)(nil)
