apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: naisdevice-approval
  namespace: naisdevice
  labels:
    team: naisdevice
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      external:
        - host: login.microsoftonline.com
        - host: graph.microsoft.com
  port: 80
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
    {{/each}}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  envFrom:
    - secret: naisdevice-approval