app: naisdevice-approval
namespace: naisdevice
team: naisdevice
env:
  DOMAIN: nav.no
  ACCESS_GROUP: ffd89425-c75c-4618-b5ab-67149ddbbc2d
  AAD_CLIENT_ID: 954ef047-2f2b-49b8-ab8b-6b86f1fe6982
ingresses:
  - https://naisdevice-approval.prod-gcp.nais.io