#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

rm -f ./apiserver*.deb

fpm \
	--verbose \
	--output-type deb \
	--input-type dir \
	--name apiserver \
	--version "${1:-Unknown}" \
	--vendor "NAV / nais team" \
	--maintainer "NAV / nais team" \
	--description "naisdevice apiserver handles gateways and devices and distributes wireguard configurations for them" \
	--url https://github.com/nais/device \
	--deb-systemd packaging/controlplane/apiserver/apiserver.service \
	--deb-systemd-enable \
	--deb-systemd-auto-start \
	--deb-systemd-restart-after-upgrade \
	--depends wireguard \
	bin/controlplane/apiserver=/usr/bin/apiserver
