#!/usr/bin/env bash
CONFIG_PATH=/usr/local/etc/nais-device

if [ $# -ne 2 ]; then
	echo "This script fetches the appropriate secret using the gcloud api"
	echo "and writes it to the api_secret file in the CONFIG_DIR as defined"
	echo "inside the source file (currently $CONFIG_PATH)"
	echo
	echo "Usage: $0 [project-name] [host-name]"
	echo "Example: $0 nais-device nais-device-azure-gw"
	exit 1
fi

SECRET_NAME="$1_$2"
API_SERVER_PASSWORD="$(gcloud --project nais-device secrets versions access latest --secret ${SECRET_NAME}_api-server-password)"

if [ $? -ne 0 ]; then
	echo "Failed to fetch API server password from gcloud."
	echo
	echo "You may be about to launch gateway-agent with incorrect credentials."
	exit 1
fi;

mkdir -p "$CONFIG_PATH" || exit 1
touch "$CONFIG_PATH"/api_secret || exit 1
chmod 600 "$CONFIG_PATH"/api_secret || exit 1
echo -n "$API_SERVER_PASSWORD" > "$CONFIG_PATH"/api_secret || exit 1
