#!/usr/bin/env bash

# This script downloads and deploys the latest release of gateway-agent

RELEASE_URL="https://api.github.com/repos/nais/device/releases/latest"
RELEASE_DATA=$(curl --show-error --silent "$RELEASE_URL")

if [ $? != 0 ]; then
	echo "Failed to fetch release information from \"$URL\""
	exit 1
fi;

RELEASE_TAG_RAW=$(echo -n "$RELEASE_DATA" | grep '"tag_name":')

if [ $? != 0 ]; then
	echo "Did not find tag name in release data"
	exit 1
fi;

RELEASE_TAG=$(echo -n "$RELEASE_TAG_RAW"| sed -E 's/.*"([^"]+)".*/\1/')

curl -LO https://github.com/nais/device/releases/download/$RELEASE_TAG/gateway-agent

if [ $? != 0 ]; then
	echo "Failed to download release agent!"
	exit 1
fi;

chmod 700 gateway-agent || exit 1
mkdir -p /opt/nais-device/bin/ || exit 1
mv gateway-agent /opt/nais-device/bin/ || exit 1
