#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

rm -f ./naisdevice*.deb

fpm \
    --verbose \
    --output-type deb \
    --input-type dir \
    --name "naisdevice" \
    --version "${1:-Unknown}" \
    --vendor "NAV / nais team" \
    --maintainer "NAV / nais team" \
    --description "naisdevice is a mechanism enabling NAVs developers to connect to internal resources in a secure and friendly manner." \
    --url https://doc.nais.io/device \
    --depends jq \
    --depends sed \
    --depends wireguard \
    --depends libnss3-tools \
    --depends openssl \
    --depends libayatana-appindicator3-1 \
    --pre-install packaging/linux/preinstall \
    --after-install packaging/linux/postinstall \
    --after-upgrade packaging/linux/postinstall \
    --deb-systemd packaging/linux/naisdevice-helper.service \
    --deb-systemd-enable \
    --deb-systemd-auto-start \
    --deb-systemd-restart-after-upgrade \
    bin/linux-client/naisdevice-helper=/usr/sbin/naisdevice-helper \
    bin/linux-client/naisdevice-agent=/usr/bin/naisdevice-agent \
    bin/linux-client/naisdevice-systray=/usr/bin/naisdevice-systray \
    packaging/linux/naisdevice.desktop=/usr/share/applications/ \
    packaging/linux/nav_bundle.crt=/usr/local/share/ca-certificates/ \
    packaging/linux/icons/=/usr/share/icons/hicolor/
