#!/bin/bash
set -o errexit

# Assert just _one_ logged-in user
user_accounts=$(loginctl list-users --output json | jq -e '[.[] | select(.uid >= 1000)]')
if jq -e 'length != 1' <<< "$user_accounts" > /dev/null; then
	echo -e "\nMore than 1 user account logged in! naisdevice only permits _one_ user account!\n"
	exit 1
fi

# Assert only whitelisted service accounts "logged in" (if logged in at all)
service_accounts=$(loginctl list-users --output  json | jq -e '[.[] | select(.uid < 1000)]')
if jq -e 'length > 0' <<< "$service_accounts" > /dev/null; then
	is_not_whitelisted=0

	whitelisted_service_accounts="gdm,"
	for account in $(echo "$service_accounts" | jq -e '.[].user'); do
		if ! grep --quiet --silent --perl-regexp "(^|,)$account(,|$)" <<< "$whitelisted_service_accounts"; then
			is_not_whitelisted=1
			break
		fi
	done

	if [[ "$is_not_whitelisted" == "1" ]]; then
		echo -e "\nYou've got service-users running on your system which require being logged in."
		echo -e "\tThis is the list of whitelisted service_accounts: $whitelisted_service_accounts"
		echo "Are you perhaps running an unsupported display manager/desktop environment? Ref: https://doc.nais.io/device/install/#ubuntu-installation"
		exit 1
	fi
fi

ln -sf /usr/bin/naisdevice-systray /usr/bin/naisdevice

user=$(echo "$user_accounts" | jq -r ".[0].user")
home=$(getent passwd "${user}" | cut -d: -f 6)

config_dir="${home}/.config/naisdevice/"
log_dir="${config_dir}/logs"
unit_file=/lib/systemd/system/naisdevice-helper.service

# shellcheck disable=SC2174
mkdir -p --mode 700 "${config_dir}"
# shellcheck disable=SC2174
mkdir -p --mode 700 "${log_dir}"

sed -i "s%@@CONFIG_DIR@@%${config_dir}%" "${unit_file}"

cp /sys/devices/virtual/dmi/id/product_serial "${config_dir}"

chown -R "${user}:" "${config_dir}"

set +e
systemctl is-active --quiet device-agent-helper.service \
	&& systemctl stop device-agent-helper.service
killall naisdevice-systray || true
killall naisdevice-agent || true
