#!/bin/sh
set -o errexit

ensure_line() {
	line="$1"
	file="$2"

	if ! grep -q "$1" "$2"; then
		sed -i -e '$a'"$line" "$file"
	fi
}

ensure_line "nav/NAV_Issuing_CA_ekstern.crt" "/etc/ca-certificates.conf"
ensure_line "nav/NAV_Partner_Issuing_CA.crt" "/etc/ca-certificates.conf"
ensure_line "nav/NAV_Partner_Sub_CA.crt" "/etc/ca-certificates.conf"
ensure_line "nav/NAV_Root_CA.crt" "/etc/ca-certificates.conf"
ensure_line "nav/NAV_Sub_CA.crt" "/etc/ca-certificates.conf"

update-ca-certificates

systemd_version="$(systemctl --version | head -n 1 | grep -o '[0-9]+' | head -n 1)"
if [[ $systemd_version -gt 255 ]]; then
	user_accounts=$(loginctl list-users -j | jq '[.[] | select(.uid >= 1000)]')
else
	user_accounts=$(loginctl list-users --output json | jq '[.[] | select(.uid >= 1000)]')
fi
echo $user_accounts

if echo "$user_accounts" | jq -e 'length != 1' >/dev/null; then
	printf "\nMore than 1 user account logged in! naisdevice only permits _one_ user account!\n"
	exit 1
fi

ln -sf /usr/bin/naisdevice-systray /usr/bin/naisdevice

user=$(echo "$user_accounts" | jq -r ".[0].user")
home=$(getent passwd "${user}" | cut -d: -f 6)

config_dir="${home}/.config/naisdevice/"
log_dir="${config_dir}/logs"

for directory in "$config_dir" "$log_dir"; do
	mkdir -p "$directory"
	chmod 700 "$directory"
done

cp /sys/devices/virtual/dmi/id/product_serial "${config_dir}"

chown -R "${user}:" "${config_dir}"

set +e
killall -9 --older-than 1m --regexp "naisdevice.*" || true
