#!/bin/sh
user=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ && ! /loginwindow/ { print $3 }' )

daemon_name="io.nais.device.helper"
destination="/Library/LaunchDaemons/${daemon_name}.plist"
launchctl list | grep -q "$daemon_name" && launchctl unload "$destination"

config_dir="/Users/${user}/Library/Application Support/naisdevice"
log_dir="${config_dir}/logs"

mkdir -p -m 0700 "${config_dir}"
mkdir -p -m 0700 "${log_dir}"

chown -R "${user}:" "${config_dir}"

cat << EOF > "$destination"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>KeepAlive</key>
        <true/>
        <key>Label</key>
        <string>io.nais.device.helper</string>
        <key>Nice</key>
        <integer>0</integer>
        <key>ProgramArguments</key>
        <array>
                <string>/Applications/naisdevice.app/Contents/MacOS/naisdevice-helper</string>
                <string>--interface</string>
                <string>utun69</string>
                <string>--config-dir</string>
                <string>$config_dir</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>StandardErrorPath</key>
        <string>/Library/Logs/device-agent-helper-err.log</string>
        <key>StandardOutPath</key>
        <string>/Library/Logs/device-agent-helper-out.log</string>
</dict>
</plist>

EOF

chmod 600 "$destination"

launchctl load "$destination"

echo "Installed service $daemon_name"

killall naisdevice-agent || true
killall naisdevice-systray || true
