// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Authenticator is an autogenerated mock type for the Authenticator type
type Authenticator struct {
	mock.Mock
}

// AuthURL provides a mock function with given fields: w, r
func (_m *Authenticator) AuthURL(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Login provides a mock function with given fields: w, r
func (_m *Authenticator) Login(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Validator provides a mock function with given fields:
func (_m *Authenticator) Validator() func(http.Handler) http.Handler {
	ret := _m.Called()

	var r0 func(http.Handler) http.Handler
	if rf, ok := ret.Get(0).(func() func(http.Handler) http.Handler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(http.Handler) http.Handler)
		}
	}

	return r0
}
