// Code generated by mockery 2.9.2. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// BucketReader is an autogenerated mock type for the BucketReader type
type BucketReader struct {
	mock.Mock
}

// ReadBucketObject provides a mock function with given fields: ctx
func (_m *BucketReader) ReadBucketObject(ctx context.Context) (io.Reader, error) {
	ret := _m.Called(ctx)

	var r0 io.Reader
	if rf, ok := ret.Get(0).(func(context.Context) io.Reader); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
