// Code generated by mockery 2.9.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeDeviceHelperServer is an autogenerated mock type for the UnsafeDeviceHelperServer type
type UnsafeDeviceHelperServer struct {
	mock.Mock
}

// mustEmbedUnimplementedDeviceHelperServer provides a mock function with given fields:
func (_m *UnsafeDeviceHelperServer) mustEmbedUnimplementedDeviceHelperServer() {
	_m.Called()
}
