---
- name: Set up bootstrap-api vm
  hosts: bootstrap_api
  roles:
    - vm_bootstrap_api

- name: Set up prometheus vm
  hosts: prometheus
  roles:
    - vm_prometheus

- name: Set up apiserver vm
  hosts: apiservers
  roles:
    - vm_apiserver

- name: Set up gateway vm
  hosts: gateways
  roles:
    - vm_gateway
  vars:
    cluter_ip: 172.16.0.2
    onprem: false

- name: Set up onprem gateway vm
  hosts: onprem_gateways
  environment: "{{ proxy_env }}"
  vars:
    onprem: true
    admin_users:
      - name: m152973
        authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO7fYA2cjne20QGuDjsVAorHikWPB5iPVzfbh/ej6pWZ vegar@sechmann.no-20190405\nssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB49qLBkoHhlnpf7HxhcjIozk2ffeOQdAwaElMbusQ9J vegar@laptux-vegar-nav"
      - name: h129009
        authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHsIXwF/eT74JubXMiAmk1Qwxs4VgZESy/JT/0gKTRG1 johnny@horvi.no-2019-05-15"
      - name: r137915
        authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDutPpwpMPlrcNYbZi/Yp3tuidx0fbH5lINAt03AUbGrjcplIas89bNVFPqEZZkjW7pToviaAVZPbWvNOc4buve/dm8PuvjiIiD/TcWlBWYVG2awYTXxIlETA6S4zklFicv2GjgdVOCV3N2ttyLYF1Q2fGHaZU1KJQg1vEcL4JtOtecmMvEG8mwXXNEHAP+gGJPwghFV7zfZRkrnT3Jcw59NjAidnRCv9d7XPNH3+/zgwl+eem20jKxBjOd8r1qFaJ3raUxvcm05BMC65O5jeUXSakz1cnD4NqO9pTwGbDLos4FCh36FmqbYZqYGLoQScw2ohOtudlJxm9c+higHuT1 stenrokke@Stens-MacBook-Pro.local"
      - name: n151873
        authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKM1uoX5nHMM1ruk1Rfjh1c/t0s1LNQh0MXtf27hC4jg cardno:000615209054"
      - name: j152316
        authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7FMHEQwqc0RiVaYzGGW54F9M4YnMqP8mJXCsMJdu3PmzoZL5bhTpMcnXbCfMXAyd0opvA2hrWCQNmGid8QWO13Fm2fNe1VkJ+UekputK15euJM0DfDRadLJJbHOFt5Bin3Te6a/9YP+415DUUlzaSncRxwKMdrTZZl80cj4xSLDZx2mqnCO6JHn+p4Vw6XtyR+tE4ocJCpV6DAG7eJqWitoW4FOnl5L1hX8gl+JAX2z8JlBg433a69fQwQfGjdPJqlJZTC1Zk7ltC4xiZ/j5JtGDfmc0ascoZnZXEuICFuZ6Y1PnH2T9t7U6uwjqe7te/EGgqDYBib/VKOTOa+nsHDQIRul1uXdRH2rul7aWUjBG8btpmcZv2cgeuKxwqLR21IG5KuK916q1Rrj3X9vR859u4KlD8KYqOEF/SkgbKMBteue4b8pqk6JK+8C1yR+0GBiRuQq+4GRArikgpew30XNZAF4/hieYqGnp+eso9GZfh4L9KFTLM8NuGt1ydzl0= kimt@avatar"
  roles:
    - vm_onprem_gateway
