---
- hosts: bootstrap_api
  roles:
    - logging
    - bootstrap-api

- hosts: prometheus
  roles:
    - logging
    - prometheus

- hosts: apiservers
  roles:
    - logging
    - apiserver

- hosts: gateways
  roles:
    - logging
    - gateway
  vars:
    K8S_CLUSTER_API_IP_ADDRESS: 172.10.0.2
    onprem: false

- hosts: onprem_gateways
  environment: "{{ proxy_env }}"
  vars:
    onprem: true
    admin_users:
      - name: m152973
        authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO7fYA2cjne20QGuDjsVAorHikWPB5iPVzfbh/ej6pWZ vegar@sechmann.no-20190405"
      - name: h129009
        authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHsIXwF/eT74JubXMiAmk1Qwxs4VgZESy/JT/0gKTRG1 johnny@horvi.no-2019-05-15"
  roles:
    - onprem-gateway
    - logging
    - gateway
