---
- name: Set up prometheus vm
  hosts: prometheus
  roles:
    - vm_prometheus

- name: Set up apiserver vm
  hosts: apiservers
  roles:
    - vm_apiserver

- name: Set up gateway vm
  hosts: gateways
  roles:
    - vm_gateway
  vars:
    onprem: false

- name: Set up onprem gateway vm
  hosts: onprem_gateways
  environment: "{{ proxy_env }}"
  vars:
    onprem: true
    admin_users:
      - name: b123034
        authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHuGnZzl2NCrBA8QMhH507yFgSLaOapwqQl5Fw6jMRms roger.bjornstad@nav.no"
      - name: m152973
        authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO7fYA2cjne20QGuDjsVAorHikWPB5iPVzfbh/ej6pWZ vegar@sechmann.no-20190405\nssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB49qLBkoHhlnpf7HxhcjIozk2ffeOQdAwaElMbusQ9J vegar@laptux-vegar-nav\nssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJYHRi0ZSwjOdL9S9blV7AdNM2LQN7aHiJp1T5dAXIgp\nssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKUFV67ZGk8kIdPvho4IBF4fLMemDNVPbhNlnaVcatIP"
      - name: h129009
        authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHsIXwF/eT74JubXMiAmk1Qwxs4VgZESy/JT/0gKTRG1 johnny@horvi.no-2019-05-15"
      - name: r137915
        authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG7XEyXBREJ9cXrHD+SbpXs+SkCNSnUYEoYLjCcVsfvd sten.ivar.rokke@nav.no"
      - name: n151873
        authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKM1uoX5nHMM1ruk1Rfjh1c/t0s1LNQh0MXtf27hC4jg cardno:000615209054"
      - name: j152316
        authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7FMHEQwqc0RiVaYzGGW54F9M4YnMqP8mJXCsMJdu3PmzoZL5bhTpMcnXbCfMXAyd0opvA2hrWCQNmGid8QWO13Fm2fNe1VkJ+UekputK15euJM0DfDRadLJJbHOFt5Bin3Te6a/9YP+415DUUlzaSncRxwKMdrTZZl80cj4xSLDZx2mqnCO6JHn+p4Vw6XtyR+tE4ocJCpV6DAG7eJqWitoW4FOnl5L1hX8gl+JAX2z8JlBg433a69fQwQfGjdPJqlJZTC1Zk7ltC4xiZ/j5JtGDfmc0ascoZnZXEuICFuZ6Y1PnH2T9t7U6uwjqe7te/EGgqDYBib/VKOTOa+nsHDQIRul1uXdRH2rul7aWUjBG8btpmcZv2cgeuKxwqLR21IG5KuK916q1Rrj3X9vR859u4KlD8KYqOEF/SkgbKMBteue4b8pqk6JK+8C1yR+0GBiRuQq+4GRArikgpew30XNZAF4/hieYqGnp+eso9GZfh4L9KFTLM8NuGt1ydzl0= kimt@avatar"
      - name: e154363
        authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDVqsPTuiE44phL2RtDpmP72ZJBOm8ZNYKRCXZu/b9r9Y4NB1Mf4OhGTyQJjITStGtD0uHXGbXlIzmC68Z1o5VinBZAaFL3LZ+NyAP7ygDixfmaAPzK118zxhuUi8BGN4chFv6MVP1Ytr2FudO/BSzk6QtlVBtwFwMlxcfEbx97QGabXXJUDkzIjXSv+ityw3a7Dv20vb2OvTc37ENsEsTmiA79x75EjLiMPV6WkzaL2WPzu14SP2GBNbx9TFpn8cCbKTOcFCq5DZcrYUtA9mMvpYkfS0zHV0Lmdwk1HDj8s1xR70EBjco1YOFzC46dsdpKKpahn4d6xwrfqsSWDq/PEuviU4EEco5PQbAUpm3ogVNpyWdF10hTSF+/NW5l3JpPfDwqwQ7d9L/FuCLINtBntvyGdywPm6Aah2S1MM+eZ2XG/zQIPADmMF+ruoQ3brFQMx2lroTmzA5lOMJ5GW68xYatOydBVGgwjq6B5jPl9Yr2eOZTqg4y5U71nQqct8C2MPeDikGDyLm76amWD/U7FFjJ1a50IXW6oYYy+JomugYgz4/mYCsLH5lVlV6RzEizeaQi6RrPX274U2/VhfAjhdEZQlj9oBZSCzaz/ZrelcS4/CnDGcsxqIWvyXnZoJTsp4ou2wcEWkLTBliPt6VECfOMQe58REEbgYeJGvIxRQ== chredvar@caveman"
  roles:
    - vm_onprem_gateway
