// Code generated by mockery v2.10.0. DO NOT EDIT.

package pb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeDeviceHelperServer is an autogenerated mock type for the UnsafeDeviceHelperServer type
type MockUnsafeDeviceHelperServer struct {
	mock.Mock
}

// mustEmbedUnimplementedDeviceHelperServer provides a mock function with given fields:
func (_m *MockUnsafeDeviceHelperServer) mustEmbedUnimplementedDeviceHelperServer() {
	_m.Called()
}
