// Code generated by mockery v2.9.4. DO NOT EDIT.

package pb

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAPIServerServer is an autogenerated mock type for the APIServerServer type
type MockAPIServerServer struct {
	mock.Mock
}

// AdminListGateways provides a mock function with given fields: _a0, _a1
func (_m *MockAPIServerServer) AdminListGateways(_a0 *AdminListGatewayRequest, _a1 APIServer_AdminListGatewaysServer) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*AdminListGatewayRequest, APIServer_AdminListGatewaysServer) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDeviceConfiguration provides a mock function with given fields: _a0, _a1
func (_m *MockAPIServerServer) GetDeviceConfiguration(_a0 *GetDeviceConfigurationRequest, _a1 APIServer_GetDeviceConfigurationServer) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*GetDeviceConfigurationRequest, APIServer_GetDeviceConfigurationServer) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetGatewayConfiguration provides a mock function with given fields: _a0, _a1
func (_m *MockAPIServerServer) GetGatewayConfiguration(_a0 *GetGatewayConfigurationRequest, _a1 APIServer_GetGatewayConfigurationServer) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*GetGatewayConfigurationRequest, APIServer_GetGatewayConfigurationServer) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: _a0, _a1
func (_m *MockAPIServerServer) Login(_a0 context.Context, _a1 *APIServerLoginRequest) (*APIServerLoginResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *APIServerLoginResponse
	if rf, ok := ret.Get(0).(func(context.Context, *APIServerLoginRequest) *APIServerLoginResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*APIServerLoginResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *APIServerLoginRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedAPIServerServer provides a mock function with given fields:
func (_m *MockAPIServerServer) mustEmbedUnimplementedAPIServerServer() {
	_m.Called()
}
