// Code generated by mockery v2.32.2. DO NOT EDIT.

package pb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeAPIServerServer is an autogenerated mock type for the UnsafeAPIServerServer type
type MockUnsafeAPIServerServer struct {
	mock.Mock
}

// mustEmbedUnimplementedAPIServerServer provides a mock function with given fields:
func (_m *MockUnsafeAPIServerServer) mustEmbedUnimplementedAPIServerServer() {
	_m.Called()
}

// NewMockUnsafeAPIServerServer creates a new instance of MockUnsafeAPIServerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeAPIServerServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeAPIServerServer {
	mock := &MockUnsafeAPIServerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
