// Code generated by mockery v2.9.4. DO NOT EDIT.

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockAPIServerClient is an autogenerated mock type for the APIServerClient type
type MockAPIServerClient struct {
	mock.Mock
}

// AdminListGateways provides a mock function with given fields: ctx, in, opts
func (_m *MockAPIServerClient) AdminListGateways(ctx context.Context, in *AdminListGatewayRequest, opts ...grpc.CallOption) (APIServer_AdminListGatewaysClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 APIServer_AdminListGatewaysClient
	if rf, ok := ret.Get(0).(func(context.Context, *AdminListGatewayRequest, ...grpc.CallOption) APIServer_AdminListGatewaysClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(APIServer_AdminListGatewaysClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *AdminListGatewayRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeviceConfiguration provides a mock function with given fields: ctx, in, opts
func (_m *MockAPIServerClient) GetDeviceConfiguration(ctx context.Context, in *GetDeviceConfigurationRequest, opts ...grpc.CallOption) (APIServer_GetDeviceConfigurationClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 APIServer_GetDeviceConfigurationClient
	if rf, ok := ret.Get(0).(func(context.Context, *GetDeviceConfigurationRequest, ...grpc.CallOption) APIServer_GetDeviceConfigurationClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(APIServer_GetDeviceConfigurationClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *GetDeviceConfigurationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGatewayConfiguration provides a mock function with given fields: ctx, in, opts
func (_m *MockAPIServerClient) GetGatewayConfiguration(ctx context.Context, in *GetGatewayConfigurationRequest, opts ...grpc.CallOption) (APIServer_GetGatewayConfigurationClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 APIServer_GetGatewayConfigurationClient
	if rf, ok := ret.Get(0).(func(context.Context, *GetGatewayConfigurationRequest, ...grpc.CallOption) APIServer_GetGatewayConfigurationClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(APIServer_GetGatewayConfigurationClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *GetGatewayConfigurationRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *MockAPIServerClient) Login(ctx context.Context, in *APIServerLoginRequest, opts ...grpc.CallOption) (*APIServerLoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *APIServerLoginResponse
	if rf, ok := ret.Get(0).(func(context.Context, *APIServerLoginRequest, ...grpc.CallOption) *APIServerLoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*APIServerLoginResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *APIServerLoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
