// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bucket

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Open provides a mock function for the type MockClient
func (_mock *MockClient) Open(ctx context.Context) (Object, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (Object, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) Object); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockClient_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Open(ctx interface{}) *MockClient_Open_Call {
	return &MockClient_Open_Call{Call: _e.mock.On("Open", ctx)}
}

func (_c *MockClient_Open_Call) Run(run func(ctx context.Context)) *MockClient_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Open_Call) Return(object Object, err error) *MockClient_Open_Call {
	_c.Call.Return(object, err)
	return _c
}

func (_c *MockClient_Open_Call) RunAndReturn(run func(ctx context.Context) (Object, error)) *MockClient_Open_Call {
	_c.Call.Return(run)
	return _c
}
