#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

echo "sudoing.. enter pw:"
sudo echo "..."

#sudo xattr -r -d com.apple.quarantine ./bin/device-agent
#sudo xattr -r -d com.apple.quarantine ./bin/device-agent-helper

./bin/device-agent --binary-dir="${DIR}/bin"
