name: Test, build and deploy the approval app
on:
  push:
    paths:
      - 'approval/**'
      - '.github/workflows/approval-test-and-deploy.yml'

defaults:
  run:
    working-directory: ./approval

jobs:
  test:
    name: Run unit tests and static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output some debug information about the PHP version
        run: |
          php -v
          php -i
          php -m
      - name: Validate composer files
        run: composer validate --strict
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-approval-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-approval-
      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest --no-ansi -o
      - name: Run unit tests
        run: composer run test
      - name: Run static analysis
        run: composer run sa