name: Test, build and deploy the approval app
on:
  push:
    paths:
      - 'approval/**'
      - '.github/workflows/approval-test-and-deploy.yml'

defaults:
  run:
    working-directory: ./approval

jobs:
  test:
    name: Run unit tests and static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output some debug information about the PHP version
        run: |
          php -v
          php -i
          php -m
      - name: Validate composer files
        run: composer validate --strict
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-ansi
      - name: Run unit tests
        run: composer run test
      - name: Run static analysis
        run: composer run sa