name: Test and Build

on: [pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "macos-15"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: jdx/mise-action@v2
      - if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install --yes build-essential
      - run: "mise run test"
      - run: "mise run check"
      - run: "go vet ./..."
      - run: "mise run build"
