name: Test and Build
on: [pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        mise-task: ["test", "staticcheck", "vulncheck", "vet", "build"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install --yes build-essential
      - name: mise run ${{ matrix.mise-task }}
        run: mise run ${{ matrix.mise-task }}
