name: Test and Build

on: [pull_request]

env:
  go_version: '1.21.4'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
            os: ["ubuntu-22.04", "macOS-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go_version }}
      - if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt update
          sudo apt install --yes build-essential
      - run: "make test"
      - run: "make check"
      - run: "go vet ./..."
      - run: "make local"
