name: Test and Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt update
          sudo apt remove --yes libappindicator3-dev
          sudo apt install --yes build-essential ruby ruby-dev rubygems libgtk-3-dev libayatana-appindicator3-dev
          #sudo gem install --no-document fpm -v 1.13.1
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.21"
      - name: Test and Build
        run: |
          make local
