name: Update PPA repo

on:
  workflow_run:
    workflows: [ "Test, build and release" ]
    branches: [ master ]
    types:
      - completed
  workflow_dispatch:

jobs:
  update-ppa-repo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Latest version
        id: latest_version
        uses: abatilo/release-info-action@5876e1e74bcf971982cc7bef9b65a8814621cf44
        with:
          owner: nais
          repo: device
      - name: Add new deb to ppa
        id: update_ppa
        env:
          LATEST: ${{ steps.latest_version.outputs.latest_tag }}
          LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
          PPA_REPO_KEY: ${{ secrets.PPA_REPO_KEY }}
          PPA_GPG_PRIVATE_KEY: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          PPA_GPG_PASSPHRASE: ${{ secrets.PPA_GPG_PASSPHRASE }}
          EMAIL: aura@nav.no
        run: |
          echo "Version ${LATEST} was released at ${LATEST_DATE}"
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${PPA_REPO_KEY}"
          git clone git@github.com:nais/nais-ppa.git pparepo
          cd pparepo

          # 'Unpack' deb file for PPA purposes
          sudo apt update
          sudo apt install dpkg-dev apt-utils
          wget https://github.com/nais/device/releases/download/${LATEST}/naisdevice.deb -O naisdevice-${LATEST}.deb
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
          apt-ftparchive release . > Release

          # Set-up GPG and sign repo artifacts
          echo -n ${PPA_GPG_PRIVATE_KEY} | base64 -d > /tmp/private.key
          gpg --import /tmp/private.key
          echo ${PPA_GPG_PASSPHRASE} | gpg --batch --yes --passphrase-fd 0 --default-key "${EMAIL}" -abs -o - Release > Release.gpg
          echo ${PPA_GPG_PASSPHRASE} | gpg --batch --yes --passphrase-fd 0 --default-key "${EMAIL}" --clearsign -o - Release > InRelease

          # Commit and push changes
          git config user.email "${EMAIL}"
          git config user.name "naisdevice pipeline"
          git add .
          git --no-pager diff --cached
          git commit -a -m "Add version ${LATEST} of naisdevice.deb"
          git push
