name: Update PPA

on:
  workflow_run:
    workflows: [ "Release naisdevice frontends" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  update-ppa-repo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Latest version
        id: latest_version
        uses: abatilo/release-info-action@5876e1e74bcf971982cc7bef9b65a8814621cf44
        with:
          owner: nais
          repo: device
      - name: Add new deb to ppa
        id: update_ppa
        env:
          LATEST: ${{ steps.latest_version.outputs.latest_tag }}
          LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
          PPA_REPO_KEY: ${{ secrets.PPA_REPO_KEY }}
          EMAIL: aura@nav.no
        run: |
          echo "Version ${LATEST} was released at ${LATEST_DATE}"
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${PPA_REPO_KEY}"
          git clone git@github.com:nais/nais-ppa.git pparepo
          cd pparepo

          # Fetch latest deb
          wget https://github.com/nais/device/releases/download/${LATEST}/naisdevice.deb -O naisdevice-${LATEST}.deb

          # Commit and push changes
          git config user.email "${EMAIL}"
          git config user.name "naisdevice pipeline"
          git add naisdevice-${LATEST}.deb
          git --no-pager diff --cached
          git commit --all --message "Add version ${LATEST} of naisdevice.deb"
          git push
