name: Update PPA

on:
  workflow_run:
    workflows: ["Release naisdevice"]
    types:
      - completed
    tags:
      - **
  workflow_dispatch:

jobs:
  update-ppa-repo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Get Latest version
        id: latest_version
        uses: abatilo/release-info-action@5774bec4e3eabad433b4ae8f625e83afa0e7bb22
        with:
          owner: nais
          repo: device
      - name: Add new deb to ppa
        id: update_ppa
        env:
          LATEST: ${{ steps.latest_version.outputs.latest_tag }}
          LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
          PPA_REPO_KEY: ${{ secrets.PPA_REPO_KEY }}
          EMAIL: aura@nav.no
        run: |
          echo "Version ${LATEST} was released at ${LATEST_DATE}"

          if [[ "${LATEST}" == "null" ]]; then
            echo "Invalid version!"
            exit 1
          fi

          eval "$(ssh-agent -s)"
          ssh-add - <<< "${PPA_REPO_KEY}"
          git clone git@github.com:nais/nais-ppa.git pparepo
          cd pparepo

          # Fetch latest deb
          wget https://github.com/nais/device/releases/download/${LATEST}/naisdevice.deb -O naisdevice-${LATEST}.deb
          wget https://github.com/nais/device/releases/download/${LATEST}/naisdevice-tenant.deb -O naisdevice-tenant-${LATEST}.deb

          # Commit and push changes
          git config user.email "${EMAIL}"
          git config user.name "naisdevice pipeline"
          git add naisdevice-${LATEST}.deb
          git add naisdevice-tenant-${LATEST}.deb
          git --no-pager diff --cached
          git commit --all --message "Add version ${LATEST} of naisdevice.deb"
          git push

  upload-gar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Get Latest version
        id: latest_version
        uses: abatilo/release-info-action@5774bec4e3eabad433b4ae8f625e83afa0e7bb22
        with:
          owner: nais
          repo: device

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d" # ratchet:google-github-actions/auth@v1.0.0
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "gh-naisdevice@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          install_components: beta

      - name: 'Upload new deb file to Google repository'
        env:
          LATEST: ${{ steps.latest_version.outputs.latest_tag }}
          LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
        run: |
          echo "Version ${LATEST} was released at ${LATEST_DATE}"
          
          if [[ "${LATEST}" == "null" ]]; then
            echo "Invalid version!"
            exit 1
          fi

          # Fetch latest debs
          wget https://github.com/nais/device/releases/download/${LATEST}/naisdevice.deb -O naisdevice-${LATEST}.deb
          wget https://github.com/nais/device/releases/download/${LATEST}/naisdevice-tenant.deb -O naisdevice-tenant-${LATEST}.deb
          
          # Upload to GAR
          gcloud --project nais-io beta artifacts apt upload nais-ppa --quiet --source naisdevice-${LATEST}.deb --location europe-north1
          gcloud --project nais-io beta artifacts apt upload nais-ppa --quiet --source naisdevice-tenant-${LATEST}.deb --location europe-north1
