name: Update winget repo

on:
  workflow_dispatch:

jobs:
  create-pr-in-winget-pkg-repo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Latest version
        id: latest_version
        uses: abatilo/release-info-action@5876e1e74bcf971982cc7bef9b65a8814621cf44
        with:
          owner: nais
          repo: device
      - name: Add new msi
        id: update_winget
        env:
          LATEST: ${{ steps.latest_version.outputs.latest_tag }}
          LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
          WINGET_REPO_KEY: ${{ secrets.WINGET_REPO_KEY }}
        run: |
          echo "Version ${LATEST} was released at ${LATEST_DATE}"
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${WINGET_REPO_KEY}"

          wget https://github.com/nais/device/releases/download/${LATEST}/naisdevice.msi -O naisdevice.msi
          MSICHECKSUM=$(sha256sum naisdevice.msi | awk {'print $1}')

          git clone git@github.com:nais/winget-pkgs.git wingetrepo
          cd wingetrepo

          mkdir -p manifests/n/NAV/naisdevice/${LATEST}
          cd manifests/n/NAV/naisdevice/${LATEST}
          cat <<EOF >naisdevice.yaml
          PackageIdentifier: NAV.naisdevice
          PackageVersion: ${LATEST}
          PackageName: naisdevice
          Publisher: NAV
          License: MIT
          LicenseUrl: https://github.com/nais/device/LICENSE
          Tags:
          - vpn
          - security
          - nais
          PackageUrl: https://github.com/nais/device
          Installers:
          - Architecture: x64
            InstallerUrl: https://github.com/nais/device/releases/download/$LATEST/naisdevice.msi
            InstallerSha256: ${MSICHECKSUM}
            InstallerType: msi
          ShortDescription: A mechanism enabling NAVs developers to connect to internal resources in a secure and friendly manner.
          PackageLocale: en-US
          ManifestType: singleton
          ManifestVersion: 1.0.0
          EOF

          cat manifests/n/NAV/naisdevice/${LATEST}/naisdevice.yaml

          # Commit and push changes
          #git config user.email "${EMAIL}"
          #git config user.name "naisdevice pipeline"
          #git add .
          #git --no-pager diff --cached
          #git commit -a -m "Add version ${LATEST} of naisdevice.msi"
          #git push
